---
title: "Achievements"
---

# Achievements

## Academic and Professional Awards

### Empowerment Scholarship Winner - AEMS Summer School

**Date:** 2021\
**Institution:** BOKU University, Vienna, Austria\
**Details:** One of 10 fully funded Empowerment Scholarships winners and the only Pakistani to have won this scholarship.

### Best Essay Writer of the Year at Provincial Level

**Date:** 2016\
**Awarding Body:** Provincial Level Essay Competition\
**Details:** Recognized as the best essay writer in the province.

### 2nd Position at 24th Intra Board Science Essay Competition

**Date:** 2015\
**Awarding Body:** Intra Board Science Essay Competition\
**Details:** Secured 2nd position in the science essay competition.

### 7th Position in Matric at BISE Level

**Date:** 2016\
**Awarding Body:** Board of Intermediate and Secondary Education\
**Details:** Achieved 7th position in the matriculation examination.

### Vice Rector’s Honorary List - Spring 2020 Semester

**Date:** 2020\
**Institution:** Forman Christian College (A Chartered University)\
**Details:** Included in the Vice Rector’s Honorary List for outstanding academic performance in the Spring 2020 semester.

### Volunteer and Leadership Roles

**Details:** Actively volunteered and held leadership positions in various university clubs and international festivals, including the Lahore International Children Film Festival, Lahore Literary Festival, Faiz International Festival, Falling Walls Lab Foundation, and more.
