---
title: "Certifications"
---

# Certifications

### Verified Certification - HarvardX: Entrepreneurship in Emerging Economies

**Date:** April 2021\
**Institution:** HarvardX\
**Details:** Earned a verified certificate for completing the course on Entrepreneurship in Emerging Economies.

### Toyota 5S Methodology Training Certification

**Details:** Completed training on the Toyota 5S Methodology.

### Connect Program Fellow - Spring Semester

**Date:** 2021\
**Institution:** Soliya USA\
**Details:** Selected as a fellow for the Connect Program, demonstrating skills in dialogue facilitation and international cultural exchange.

### Certification in Introduction to Dialogue Facilitation

**Institution:** Soliya USA\
**Details:** Completed certification in facilitating dialogue among diverse groups.

### Certification - National Financial Literacy Training Program

**Institution:** State Bank of Pakistan\
**Details:** Certified in financial literacy through the National Financial Literacy Training Program.

### Certification Recipient - OPEN (US Department of State): English for Business and Entrepreneurship

**Details:** Awarded a certification for completing the English for Business and Entrepreneurship course by OPEN (US Department of State).
